FROM node:20-alpine
WORKDIR /app
COPY package.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm install
COPY . .
EXPOSE 80
CMD ["npm", "run", "dev", "--", "--port", "80", "--host", "0.0.0.0"]
