services:
  frontend:
    build: ./frontend
    container_name: video-trans-frontend
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - project_network

  api:
    build: ./api
    container_name: video-trans-api
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/video_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - project_network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: video_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - project_network

  worker:
    build:
      context: ./worker
      cache_from:
        - video-trans-worker-base:latest
    container_name: video-trans-worker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - .env
    environment:
      - COQUI_TOS_AGREED=1
    depends_on:
      - redis
    networks:
      - project_network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - project_network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - project_network

volumes:
  minio_data:
  postgres_data:

networks:
  project_network:
